package Chocolates;
public class Chocolate{
protected double percentMilk;
protected double percentChoco;
protected String chocolateName;
protected String confectioner;
protected int price;

public Chocolate(){
super();
//autogenerated constructor stub

this.chocolateName = "Chocolate";
this.confectioner = "Willy Wonka";
this.percentChoco = 5.35;
this.percentMilk = 7.35;
this.price = 10;
}
public int getPrice(){
return this.price;}
public void getComposition(){
System.out.println("The chocolate compostion is:");
System.out.println("The % milk is:"+ percentMilk);
System.out.println("The % choco is:"+ percentChoco);}
@Override
public String toString(){
return "--Chocolate--\n";
}
}